name: docker

on:
  push:
    branches:
      - master

jobs:
  docker:
    name: build docker image
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log into registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push Docker images
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64,linux/arm64
          tags: vesoft/nebula-console:nightly, vesoft/nebula-console:v3-nightly
          push: true
