name: pull_request

on:
  pull_request:
    branches:
      - master
      - release-**
    paths-ignore:
      - '**.md'
      - '.gitignore'
      
defaults:
  run:
    shell: bash
    
env:
  GOPROXY: ${{ vars.GOPROXY }}
  
jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
      - uses: actions/checkout@v4
      - name: setup-go 1.18
        uses: actions/setup-go@v5
        with:
          go-version: 1.18
      - name: Fmt
        run: |
          make fmt
          files=$(git status -s)
          [[ "$files" == "" ]] && exit 0 || exit 1

  build:
    name: build
    needs: lint
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os:
          - linux
          - darwin
          - windows
        arch:
          - amd64
          - arm64
          - arm
        exclude:
          - os: darwin
            arch: arm
          - os: windows
            arch: arm64
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: setup-go 1.18
        uses: actions/setup-go@v5
        with:
          go-version: 1.18
      - name: set package name
        id: name
        run: |
          output_name=nebula-console-${{ matrix.os }}-${{ matrix.arch }}-nightly
          if [ "${{ matrix.os }}" = "windows"  ]; then
              output_name+='.exe'
          fi
          echo "package_name=$output_name" >> $GITHUB_OUTPUT
      - name: generate box/blob.go for data/basketballplayer.ngql
        run: make gen
        env:
          GOOS: linux
          GOARCH: amd64
      - name: build
        run: make name=${{ steps.name.outputs.package_name }}
        env:
          GOOS: ${{ matrix.os }}
          GOARCH: ${{ matrix.arch }}
